countries=("Spain", "Belgium", "United Kingdom", "France", "Netherlands")
capitals = set(["Madrid", "Brussels", "London", "Paris", "Amsterdam","Madrid"])
print(f"There are {len(countries)} countries and {len(capitals)} capitals.")
unique_cities = set(capitals)
print(unique_cities)
combined = (countries + tuple(unique_cities))
print(combined)
alphabetical_order = sorted (combined)   
print(alphabetical_order)